language: php
dist: trusty
sudo: false

services:
  - docker

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=lowest

before_script:
  - composer self-update -q
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script: "make test"

before_install: "composer install --dev"

deploy:
  provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    php: "7.1"
